# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: state.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='state.proto',
  package='state',
  syntax='proto2',
  serialized_pb=_b('\n\x0bstate.proto\x12\x05state\"\xeb\x02\n\x05State\x12\r\n\x05input\x18\x01 \x03(\x05\x12\x0e\n\x06output\x18\x02 \x03(\x05\x12\x0e\n\x06length\x18\x03 \x02(\x05\x12 \n\x05steps\x18\x04 \x03(\x0b\x32\x11.state.State.Step\x1a\x18\n\x06Vector\x12\x0e\n\x06values\x18\x01 \x03(\x02\x1a\xca\x01\n\x05Layer\x12\x1f\n\x02\x66g\x18\x01 \x02(\x0b\x32\x13.state.State.Vector\x12\x1f\n\x02ig\x18\x02 \x02(\x0b\x32\x13.state.State.Vector\x12\x1f\n\x02og\x18\x03 \x02(\x0b\x32\x13.state.State.Vector\x12\x1e\n\x01i\x18\x04 \x02(\x0b\x32\x13.state.State.Vector\x12\x1e\n\x01h\x18\x05 \x02(\x0b\x32\x13.state.State.Vector\x12\x1e\n\x01\x63\x18\x06 \x02(\x0b\x32\x13.state.State.Vector\x1a*\n\x04Step\x12\"\n\x06layers\x18\x01 \x03(\x0b\x32\x12.state.State.Layer')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_STATE_VECTOR = _descriptor.Descriptor(
  name='Vector',
  full_name='state.State.Vector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='state.State.Vector.values', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=137,
)

_STATE_LAYER = _descriptor.Descriptor(
  name='Layer',
  full_name='state.State.Layer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fg', full_name='state.State.Layer.fg', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ig', full_name='state.State.Layer.ig', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='og', full_name='state.State.Layer.og', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='i', full_name='state.State.Layer.i', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='h', full_name='state.State.Layer.h', index=4,
      number=5, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='c', full_name='state.State.Layer.c', index=5,
      number=6, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=342,
)

_STATE_STEP = _descriptor.Descriptor(
  name='Step',
  full_name='state.State.Step',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='layers', full_name='state.State.Step.layers', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=344,
  serialized_end=386,
)

_STATE = _descriptor.Descriptor(
  name='State',
  full_name='state.State',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='input', full_name='state.State.input', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='output', full_name='state.State.output', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='length', full_name='state.State.length', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='steps', full_name='state.State.steps', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_STATE_VECTOR, _STATE_LAYER, _STATE_STEP, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=386,
)

_STATE_VECTOR.containing_type = _STATE
_STATE_LAYER.fields_by_name['fg'].message_type = _STATE_VECTOR
_STATE_LAYER.fields_by_name['ig'].message_type = _STATE_VECTOR
_STATE_LAYER.fields_by_name['og'].message_type = _STATE_VECTOR
_STATE_LAYER.fields_by_name['i'].message_type = _STATE_VECTOR
_STATE_LAYER.fields_by_name['h'].message_type = _STATE_VECTOR
_STATE_LAYER.fields_by_name['c'].message_type = _STATE_VECTOR
_STATE_LAYER.containing_type = _STATE
_STATE_STEP.fields_by_name['layers'].message_type = _STATE_LAYER
_STATE_STEP.containing_type = _STATE
_STATE.fields_by_name['steps'].message_type = _STATE_STEP
DESCRIPTOR.message_types_by_name['State'] = _STATE

State = _reflection.GeneratedProtocolMessageType('State', (_message.Message,), dict(

  Vector = _reflection.GeneratedProtocolMessageType('Vector', (_message.Message,), dict(
    DESCRIPTOR = _STATE_VECTOR,
    __module__ = 'state_pb2'
    # @@protoc_insertion_point(class_scope:state.State.Vector)
    ))
  ,

  Layer = _reflection.GeneratedProtocolMessageType('Layer', (_message.Message,), dict(
    DESCRIPTOR = _STATE_LAYER,
    __module__ = 'state_pb2'
    # @@protoc_insertion_point(class_scope:state.State.Layer)
    ))
  ,

  Step = _reflection.GeneratedProtocolMessageType('Step', (_message.Message,), dict(
    DESCRIPTOR = _STATE_STEP,
    __module__ = 'state_pb2'
    # @@protoc_insertion_point(class_scope:state.State.Step)
    ))
  ,
  DESCRIPTOR = _STATE,
  __module__ = 'state_pb2'
  # @@protoc_insertion_point(class_scope:state.State)
  ))
_sym_db.RegisterMessage(State)
_sym_db.RegisterMessage(State.Vector)
_sym_db.RegisterMessage(State.Layer)
_sym_db.RegisterMessage(State.Step)


# @@protoc_insertion_point(module_scope)
